name: Housekeeping

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-add-reviewer:
    name: Auto add reviewer to PR
    uses: celestiaorg/.github/.github/workflows/reusable_housekeeping.yml@v0.2.2
    secrets: inherit
    permissions:
      issues: write
      pull-requests: write
    with:
      run-auto-request-review: true

  auto-add-assignee:
    # ignore dependabot PRs
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Assign PR to creator
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Set pull_request url and creator login
        # yamllint disable rule:line-length
        run: |
          echo "PR=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "CREATOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
        # yamllint enable rule:line-length
      - name: Assign PR to creator
        run: gh pr edit ${{ env.PR }} --add-assignee ${{ env.CREATOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
